# Generated by Django 4.2.2 on 2023-06-21 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_book_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowedbook',
            old_name='due_date',
            new_name='return_to_date',
        ),
        migrations.RemoveField(
            model_name='borrowedbook',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='returned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowedbook',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books_borrowed', to='base.book'),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrowed_books', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='borrowed_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
