# Generated by Django 4.2.2 on 2023-06-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_borrowedbook_book_alter_borrowedbook_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='return_to_date',
        ),
    ]
