# Generated by Django 4.2.2 on 2023-06-22 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_borrowedbook_return_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='return_to_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 19, 54, 28, 535176)),
        ),
    ]
