# Generated by Django 4.2.2 on 2023-06-22 21:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_borrowedbook_return_to_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowedbook',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='borrowedbook',
            name='return_to_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 23, 25, 9, 629770)),
        ),
    ]
